language = "C"
include_guard = "LEZ_FAUCET_FFI_H"
pragma_once = true
documentation = true
usize_is_size_t = true

[parse]
parse_deps = false

[export]
include = [
  "LezFaucetClient",
  "LezFaucetClientOutput",
  "lez_faucet_client_new",
  "lez_faucet_client_destroy",
  "lez_faucet_string_free",
  "lez_faucet_get_info",
  "lez_faucet_inspect_recipient",
  "lez_faucet_request_drop",
  "lez_faucet_cancel",
]
